language: ruby
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  campfire:
    rooms:
      - secure: "nK5kN3xf43qNUzQ2e+3hCD1Iy/XzqMS1EOm1aDyvbi1nv4xHD7ZkKTRgFAPYGJj/SpuSkIlWbFybYUfeGe9SVrg9/C70vlNmmuNkK2YV106qd5IemB65qzVb35yU7kyF84u5/kAHg8EdWfXsBYxB6KoXJoql1lGCYQMaH0L6Rb8="
    on_success: change
    on_failure: change
